recipes:
    global:
        - dotfiles::gitconfig
        - dotfiles::vim
    mac_os_x:
        - osxdefaults::set_terminal_profile
        - osxdefaults::set_a_blazingly_fast_keyboard_repeat_rate
        - osxdefaults::prevent_time_machine_from_prompting_to_use_new_hard_drives_as_backup_volume
        - osxdefaults::finder_new_finder_windows_shows_homefolder
attributes:
    homebrewalt:
        apps:
            - git
            - git-extras
            - wget